apiVersion: v1
kind: Pod
metadata:
  name: imgvol 
spec:
  containers:
    - name: echoserver 
      image: quay.io/ramalama/ramalama:latest
      volumeMounts:
        - name: volume
          mountPath: /volume
  volumes:
    - name: volume
      image:
        reference: cgr.dev/chainguard/busybox:latest
        pullPolicy: IfNotPresent
